
import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { FileText, Download, Share2, Search, Filter } from "lucide-react";

const ReportHistory = () => {
    const history = [
        { id: 1, name: "SOC 2 Readiness Report", date: "2026-01-24 10:30 AM", user: "Admin User", size: "2.4 MB" },
        { id: 2, name: "Weekly Executive Summary", date: "2026-01-23 09:00 AM", user: "System (Auto)", size: "1.1 MB" },
        { id: 3, name: "Vulnerability Scan Results", date: "2026-01-22 04:15 PM", user: "SecOps Team", size: "5.8 MB" },
        { id: 4, name: "Quarterly Risk Assessment", date: "2026-01-15 02:00 PM", user: "Risk Manager", size: "3.2 MB" },
    ];

    return (
        <div className="space-y-6 animate-in fade-in">
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
                <div>
                    <h2 className="text-2xl font-bold tracking-tight">Report History</h2>
                    <p className="text-muted-foreground">Archive of all generated reports and exports.</p>
                </div>
                <div className="flex gap-2 w-full md:w-auto">
                    <div className="relative flex-1 md:w-64">
                        <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                        <Input placeholder="Search reports..." className="pl-8" />
                    </div>
                    <Button variant="outline" size="icon"><Filter className="w-4 h-4" /></Button>
                </div>
            </div>

            <Card>
                <CardHeader>
                    <CardTitle className="text-lg">Generated Reports</CardTitle>
                </CardHeader>
                <CardContent>
                    <Table>
                        <TableHeader>
                            <TableRow>
                                <TableHead>Report Name</TableHead>
                                <TableHead>Generated Date</TableHead>
                                <TableHead>Generated By</TableHead>
                                <TableHead>Size</TableHead>
                                <TableHead className="text-right">Actions</TableHead>
                            </TableRow>
                        </TableHeader>
                        <TableBody>
                            {history.map((item) => (
                                <TableRow key={item.id}>
                                    <TableCell className="font-medium">
                                        <div className="flex items-center gap-3">
                                            <div className="p-2 bg-primary/10 rounded">
                                                <FileText className="w-4 h-4 text-primary" />
                                            </div>
                                            {item.name}
                                        </div>
                                    </TableCell>
                                    <TableCell>{item.date}</TableCell>
                                    <TableCell>{item.user}</TableCell>
                                    <TableCell>{item.size}</TableCell>
                                    <TableCell className="text-right">
                                        <div className="flex items-center justify-end gap-2">
                                            <Button variant="ghost" size="sm" className="h-8"><Share2 className="w-4 h-4 mr-2" /> Share</Button>
                                            <Button variant="outline" size="sm" className="h-8"><Download className="w-4 h-4 mr-2" /> Download</Button>
                                        </div>
                                    </TableCell>
                                </TableRow>
                            ))}
                        </TableBody>
                    </Table>
                </CardContent>
            </Card>
        </div>
    );
};

export default ReportHistory;
